[Icon Theme]
Name=Faenza-Cupertino-Dark
Comment=Dark panel icons for Faunza-Cupertino from Elementary-Dark.
Inherits=Faenza-Cupertino

Example=directory-x-normal

#Directory list
Directories=panel/16,panel/22,panel/24,panel/48,

[panel/16]
Size=16
Context=Status
Type=Fixed

[panel/22]
Size=22
Context=Status
Type=Fixed

[panel/24]
Size=24
Context=Status
Type=Fixed

[panel/48]
Size=48
Context=Status
Type=Scalable
