#!/bin/sh

set -e

lb config noauto \
	--apt-recommends false \
	--architecture i386 \
	--archive-areas "main contrib non-free" \
	--binary-images iso-hybrid \
	--clean \
	--debian-installer live \
	--debian-installer-distribution daily \
	--debian-installer-gui true \
	--iso-publisher moihack \
	--distribution jessie \
	--firmware-binary true \
	--firmware-chroot true \
	--ignore-system-defaults \
	--linux-flavours 686-pae \
	--mode debian \
	--system live \
	--linux-packages "linux-image linux-headers" \
	--win32-loader true \
"${@}"
